# Generated by Django 2.1.3 on 2018-11-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dreamreal',
        ),
    ]
